services:
  db:
    image: mysql:latest
    container_name: mysql-cn
    restart: always
    env_file:
      - ".env"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1" ]
      timeout: 20s
      retries: 10
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py makemigrations clinic --noinput &&
             python manage.py migrate --noinput &&
             python manage.py initialize_data &&
             python manage.py collectstatic --noinput &&
             (python3 manage.py createsuperuser --noinput || true) &&
             python manage.py runserver 0.0.0.0:8000"

    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
volumes:
  data: